### ISSUE TITLE
Documentation: Working examples

### ISSUE THREAD

**Issue by carlskii** [codesandbox/sandpack#721]
Hi, 

I've been trying to get some of the examples from the documentation to work. Might just be me, but nothing seems to work. I've tried the Svelte and React examples. Most of the examples reference a variable called `files` in the code snippet example. Where is `files` defined ? 

Could you please provide some complete working examples for the supported frameworks. 

Also, for the Svelte demo it might be more useful to show an example using SvelteKit which is starting to become more of a replacement for Svelte.

**Comment by danilowoz** [comment]
Hey, thanks for the feedback!

> Most of the examples reference a variable called files in the code snippet example.

Are you talking about the following snippet of code? I'm not if I got the problem, because `files` is defined right before the Sandpack component. 
<img width="956" alt="Screenshot 2023-02-17 at 10 52 26" src="https://user-images.githubusercontent.com/4838076/219626623-6669e137-b843-4fbf-8fcf-81b0d5ad91c3.png">

> SvelteKit
We're currently working on it. SvelteKit uses `async_hooks` Node.js API, which Nodebox doesn't support yet.

**Comment by carlskii** [comment]
OK thanks maybe that's my problem - I'm trying to use this in SvelteKit. I'll try agin using Svelte.

**Comment by carlskii** [comment]
OK so I have a my main Svelte `main.js` defined as per the code snippet above. However when I run the Svelte App it errors: 

```
src/main.js (7:4)
5:   
6:   return (
7:     <Sandpack
       ^
8:       files={files} 
9:       theme="light" 
SyntaxError: Unexpected token (7:4) in /Users/cbourne/Downloads/svelte-app/src/main.js
    at Parser.pp$4.raise (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:19551:13)
    at Parser.pp$9.unexpected (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:16845:8)
    at Parser.pp$5.parseExprAtom (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18926:10)
    at Parser.pp$5.parseExprSubscripts (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18718:19)
    at Parser.pp$5.parseMaybeUnary (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18684:17)
    at Parser.pp$5.parseExprOps (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18611:19)
    at Parser.pp$5.parseMaybeConditional (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18594:19)
    at Parser.pp$5.parseMaybeAssign (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18561:19)
    at Parser.pp$5.parseParenAndDistinguishExpression (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:19022:28)
    at Parser.pp$5.parseExprAtom (/Users/cbourne/Downloads/svelte-app/node_modules/rollup/dist/shared/rollup.js:18885:41)


[2023-02-17 11:32:29] waiting for changes...
```
